// Series manifest — one card per project. status: "available" | "coming".
// Flip a project to "available" once its data.js + fulls.js exist under reader/projects/<id>/.
window.ACADEMY_PROJECTS = [
  { id: "01-reaction-diffusion", title: "Reaction-Diffusion", tier: "easy", language: "Python", status: "available",
    pitch: "Two invisible chemicals spread and react on your GPU — and coral, cells, and worms grow out of the math." },
  { id: "02-fluid", title: "Fluid Simulator", tier: "medium", language: "Python", status: "available",
    pitch: "Stir a box of incompressible ink — semi-Lagrangian advection, a real pressure solve, and swirls that answer your hand." },
  { id: "03-fire", title: "Fire & Smoke", tier: "medium", language: "Python", status: "available",
    pitch: "Heat rises, flames lick, smoke shrouds the glow — your fluid solver becomes a bonfire." },
  { id: "04-lightning", title: "Lightning", tier: "easy-med", language: "Python", status: "available",
    pitch: "Recursive bolts fork across the sky, leave glowing ghosts, and flash the whole world white." },
  { id: "05-terrain-erosion", title: "Terrain Erosion", tier: "medium", language: "Python", status: "available",
    pitch: "Grow fractal mountains, then let rain, rivers, and deep time carve them into canyons." },
  { id: "06-particle-life-3d", title: "Particle Life 3D", tier: "medium", language: "Python", status: "available",
    pitch: "Give particles a species and an opinion of each other, then build the spatial hash that lets 30,000 of them live at once." },
  { id: "07-particle-painting", title: "Particle Painting", tier: "easy-med", language: "Python", status: "available",
    pitch: "Paint fire, smoke, sparks, and water onto a live canvas with a particle pool, a ring buffer, and a splat instead of a grid." },
  { id: "08-mpm-snow-sand", title: "Snow & Sand (MPM)", tier: "hard", language: "Python", status: "available",
    pitch: "One elastoplastic engine, two materials — snow that compacts and sand that finds its own angle of repose." },
  { id: "09-soft-body", title: "Soft Body", tier: "medium", language: "Python", status: "available",
    pitch: "Springs alone let a body collapse flat — internal pressure is what turns a spring loop into jelly, rubber, or a balloon." },
  { id: "10-cloth-rope", title: "Cloth & Rope", tier: "medium", language: "Python", status: "available",
    pitch: "Not springs this time — positions that simply refuse to disobey their constraints. One solver, a rope and a flag." },
  { id: "11-tornado", title: "Tornado", tier: "medium", language: "Python", status: "available",
    pitch: "Your project 02 fluid solver, given a forcing function instead of a mouse — plus debris that rides the wind it makes." },
  { id: "12-volumetric-clouds", title: "Volumetric Clouds", tier: "hard", language: "Python", status: "available",
    pitch: "No mesh, no surface — a cloud is a NUMBER at every point in space, and a camera ray reads through it." },
  { id: "13-planet-generator", title: "Planet Generator", tier: "hard", language: "Python", status: "available",
    pitch: "Sample 3D noise ON the sphere's surface and map seams simply cannot exist — a whole world from one seed." },
  { id: "14-galaxy-creator", title: "Galaxy Creator", tier: "medium", language: "Python", status: "available",
    pitch: "A logarithmic spiral, differential rotation, and 60,000 additive stars — the recipe behind every galaxy photo you've ever loved." },
  { id: "15-star-nursery", title: "Star Nursery", tier: "hard", language: "Python", status: "available",
    pitch: "Gas that pulls itself into filaments, ignites where it's densest, then blows itself apart — a full stellar lifecycle in one loop." },
  { id: "16-solar-system", title: "Solar System", tier: "medium", language: "Python", status: "available",
    pitch: "The real 1/r-squared law — and the famous integrator swap that decides whether your orbits hold for a second or forever." },
  { id: "17-plate-tectonics", title: "Plate Tectonics", tier: "hard", language: "Python", status: "available",
    pitch: "Voronoi plates with drift vectors: collisions raise mountains, partings tear rift oceans, and the higher plate wins." },
  { id: "18-ocean-currents", title: "Ocean Currents", tier: "hard", language: "Python", status: "available",
    pitch: "Wind bands push, Coriolis bends, continents block — and your fluid solver becomes a climate machine that carries heat to the poles." },
  { id: "19-strange-attractors", title: "Strange Attractors", tier: "easy", language: "Python", status: "available",
    pitch: "Three equations, no randomness — and 200,000 points that never repeat and never escape. Chaos, drawn in light." },
  { id: "20-mandelbulb", title: "Mandelbulb Explorer", tier: "hard", language: "Python", status: "available",
    pitch: "A shape with infinite detail and no mesh — rendered by an oracle that only ever answers 'you're at least THIS far away.'" },
  { id: "21-ant-colony", title: "Ant Colony", tier: "medium", language: "Python", status: "available",
    pitch: "No ant knows the map. Three sensors, one evaporating pheromone, and the colony draws highways anyway." },
  { id: "22-traffic", title: "Traffic Simulator", tier: "medium", language: "Python", status: "available",
    pitch: "Four rules per driver on a ring road — and traffic jams appear out of NOTHING, then drive backward through the cars." },
  { id: "23-evolution", title: "Evolution", tier: "hard", language: "Python", status: "available",
    pitch: "Nobody writes the foraging logic. A random neural net, energy, death, and mutation — and brains that hunt food appear on their own." },
  { id: "24-artificial-life", title: "Artificial Life", tier: "hard", language: "Python", status: "available",
    pitch: "40,000 particles, one turning rule, no notion of a 'cell' anywhere in the code — and cells assemble themselves, grow, and divide." },
  { id: "25-molecular-dynamics", title: "Molecular Dynamics", tier: "medium", language: "Python", status: "available",
    pitch: "One pair force between atoms and a symplectic integrator — and matter melts, boils, freezes, and grows crystals, all from the bottom up." },
  { id: "26-destruction", title: "Destruction Engine", tier: "hard", language: "Python", status: "coming",
    pitch: "Buildings fracturing under explosions and quakes." },
  { id: "27-voxel-sandbox", title: "Voxel Sandbox", tier: "hard", language: "Python", status: "coming",
    pitch: "A destructible voxel world — water, lava, fire, sand." },
  { id: "28-digital-brain", title: "Digital Brain", tier: "hard", language: "Python", status: "coming",
    pitch: "Millions of neurons firing with synaptic plasticity." },
  { id: "29-earth-simulator", title: "Earth Simulator", tier: "epic", language: "Python", status: "coming",
    pitch: "Atmosphere, oceans, rivers, life, and cities in one world." },
  { id: "30-universe-sandbox", title: "Universe Sandbox", tier: "epic", language: "Python", status: "coming",
    pitch: "Galaxies, black holes, stellar evolution — the capstone." },
];
