// Series manifest — one card per project. status: "available" | "coming".
// Flip a project to "available" once its data.js + fulls.js exist under reader/projects/<id>/.
window.ACADEMY_PROJECTS = [
  { id: "01-reaction-diffusion", title: "Reaction-Diffusion", tier: "easy", language: "Python", status: "available",
    pitch: "Two invisible chemicals spread and react on your GPU — and coral, cells, and worms grow out of the math." },
  { id: "02-fluid", title: "Fluid Simulator", tier: "medium", language: "Python", status: "available",
    pitch: "Stir a box of incompressible ink — semi-Lagrangian advection, a real pressure solve, and swirls that answer your hand." },
  { id: "03-fire", title: "Fire & Smoke", tier: "medium", language: "Python", status: "available",
    pitch: "Heat rises, flames lick, smoke shrouds the glow — your fluid solver becomes a bonfire." },
  { id: "04-lightning", title: "Lightning", tier: "easy-med", language: "Python", status: "available",
    pitch: "Recursive bolts fork across the sky, leave glowing ghosts, and flash the whole world white." },
  { id: "05-terrain-erosion", title: "Terrain Erosion", tier: "medium", language: "Python", status: "coming",
    pitch: "Rainfall carves rivers and canyons into procedural mountains." },
  { id: "06-particle-life-3d", title: "Particle Life 3D", tier: "medium", language: "Python", status: "coming",
    pitch: "Millions of particles, species rules, emergent 3D ecologies." },
  { id: "07-particle-painting", title: "Particle Painting", tier: "easy", language: "Python", status: "coming",
    pitch: "Paint with fire, water, smoke, and sparks." },
  { id: "08-mpm-snow-sand", title: "Snow & Sand (MPM)", tier: "hard", language: "Python", status: "coming",
    pitch: "The Material Point Method — avalanches, dunes, crumbling structures." },
  { id: "09-soft-body", title: "Soft Body", tier: "medium", language: "Python", status: "coming",
    pitch: "Jelly, rubber, and balloons that squash and bounce." },
  { id: "10-cloth-rope", title: "Cloth & Rope", tier: "medium", language: "Python", status: "coming",
    pitch: "Flags, capes, and nets under wind and gravity." },
  { id: "11-tornado", title: "Tornado", tier: "medium", language: "Python", status: "coming",
    pitch: "A rotating vortex hurling debris under a storm sky." },
  { id: "12-volumetric-clouds", title: "Volumetric Clouds", tier: "hard", language: "Python", status: "coming",
    pitch: "3D noise, ray marching, and light through weather." },
  { id: "13-planet-generator", title: "Planet Generator", tier: "hard", language: "Python", status: "coming",
    pitch: "Continents, oceans, atmosphere, and ice caps from a seed." },
  { id: "14-galaxy-creator", title: "Galaxy Creator", tier: "medium", language: "Python", status: "coming",
    pitch: "Spirals, ellipticals, nebulae, and star clusters." },
  { id: "15-star-nursery", title: "Star Nursery", tier: "hard", language: "Python", status: "coming",
    pitch: "Stars igniting inside collapsing molecular clouds." },
  { id: "16-solar-system", title: "Solar System", tier: "medium", language: "Python", status: "coming",
    pitch: "Accurate orbits, planet formation, comets." },
  { id: "17-plate-tectonics", title: "Plate Tectonics", tier: "hard", language: "Python", status: "coming",
    pitch: "Continental drift, mountains, earthquakes, volcanoes." },
  { id: "18-ocean-currents", title: "Ocean Currents", tier: "hard", language: "Python", status: "coming",
    pitch: "Global currents, temperature, salinity, storm systems." },
  { id: "19-strange-attractors", title: "Strange Attractors", tier: "easy", language: "Python", status: "coming",
    pitch: "Lorenz, Clifford, Thomas, and Aizawa in motion." },
  { id: "20-mandelbulb", title: "Mandelbulb Explorer", tier: "hard", language: "Python", status: "coming",
    pitch: "A ray-marched 3D fractal with infinite zoom." },
  { id: "21-ant-colony", title: "Ant Colony", tier: "medium", language: "Python", status: "coming",
    pitch: "Pheromone trails, foraging, and adaptation." },
  { id: "22-traffic", title: "Traffic Simulator", tier: "medium", language: "Python", status: "coming",
    pitch: "AI drivers, lights, congestion, and routing." },
  { id: "23-evolution", title: "Evolution", tier: "hard", language: "Python", status: "coming",
    pitch: "Neural creatures, mutation, predators vs. prey." },
  { id: "24-artificial-life", title: "Artificial Life", tier: "hard", language: "Python", status: "coming",
    pitch: "Millions of organisms eating, reproducing, mutating." },
  { id: "25-molecular-dynamics", title: "Molecular Dynamics", tier: "medium", language: "Python", status: "coming",
    pitch: "Atoms, bonds, heat transfer, crystal formation." },
  { id: "26-destruction", title: "Destruction Engine", tier: "hard", language: "Python", status: "coming",
    pitch: "Buildings fracturing under explosions and quakes." },
  { id: "27-voxel-sandbox", title: "Voxel Sandbox", tier: "hard", language: "Python", status: "coming",
    pitch: "A destructible voxel world — water, lava, fire, sand." },
  { id: "28-digital-brain", title: "Digital Brain", tier: "hard", language: "Python", status: "coming",
    pitch: "Millions of neurons firing with synaptic plasticity." },
  { id: "29-earth-simulator", title: "Earth Simulator", tier: "epic", language: "Python", status: "coming",
    pitch: "Atmosphere, oceans, rivers, life, and cities in one world." },
  { id: "30-universe-sandbox", title: "Universe Sandbox", tier: "epic", language: "Python", status: "coming",
    pitch: "Galaxies, black holes, stellar evolution — the capstone." },
];
